### PR TITLE
Making images 800x400

### PR DESCRIPTION
**Pull request by susanjrobertson**

### CODE REVIEW

**Comment by maban** [comment]
Uh-oh… I totally overwrote this as I was making taller images for the talks. Sorry!

I'll probably end up switching this back to shorter dimensions, just having a think about the best approach to images.

**Comment by susanjrobertson** [comment]
hahahaha! I didn't realize there were image dimensions to follow, so was trying to do what the README said. No worries, we can revert easily if we want.

**Comment by maban** [comment]
It's because I changed them while you were working on them :(

**Comment by susanjrobertson** [comment]
Well, I am not attached to a particular image or dimension so it's fine. 

Was just trying to be a good open sourcey citizen and follow the README :star2:

**Comment by maban** [comment]
Yes, you were being an amazing open sourcey citizen! I do this all the time at work: tinkering and changing stuff while people are working on it. It must drive them nuts. I am the worst!

**Pull request merged**
