### PR TITLE
Create max-quattromani

### PR DESCRIPTION
**Pull request by quattromani**
I've added my personal style guide for consideration. I think it's a nice representation and certainly inspired by many of those you have already listed. Great list - thanks for putting this together!

### CODE REVIEW

**Comment by maban** [comment]
Oh this is lovely, I'd be more than happy to add it!

**Comment by quattromani** [comment]
Oops! looks like I didn't make this an .md file, so it's not loading - do you want me to resubmit or can you change extension?

**Comment by maban** [comment]
It's easy for me to do so I'll do that now.

**Comment by maban** [comment]
Done!

**Pull request merged**
