### PR TITLE
Create 1982-dc-comics-style-guide.md

### PR DESCRIPTION
**Pull request by whitingx**
Not sure how well this might fit into the site but works as an interesting example of older, paper based style guides.

### CODE REVIEW

**Comment by bradfrost** [comment]
This is awesome! Although, ugh, it's linked to Facebook. Is there a non-Facebook version out there? I'm not trying to just be all anti-Facebook, but they do a pretty terrible job at URL preservation.

**Comment by whitingx** [comment]
@bradfrost - I've got a downloaded copy of the images - If I can't find another source I'll look at getting them hosted somewhere else and resubmit the PR.

**Comment by whitingx** [comment]
Added link to a new style guide related podcast. In regard to the _DC_ style guide hosted on Facebook - might be useful to link there for now to allow people to view and we can always update in the future should the link degrade.

**Comment by bradfrost** [comment]
Awesome, thanks so much @whitingx!

> In regard to the DC style guide hosted on Facebook - might be useful to link there for now to allow people to view and we can always update in the future should the link degrade.

That sounds like a good plan.

**Pull request merged**
