### PR TITLE
Update US Web Design System

### PR DESCRIPTION
**Pull request by afeijoo**
- Update title from US Design Standards to US Web Design System (USWDS)
- Update USWDS description
- Update screenshot

### CODE REVIEW

**Review by bradfrost — CHANGES_REQUESTED** [review]
@afeijoo thanks so much for this! Happy to merge this in, but could the new image be optimized to match the dimensions and size (roughly 10-25KB) of the other images?

**Comment by afeijoo** [comment]
@jeremyzilar Can you please provide an optimized image for this pull request ^^^?

**Comment by afeijoo** [comment]
thanks @bradfrost! Here is a new, optimized image.

**Comment by jeremyzilar** [comment]
Thanks @bradfrost ! Hope you are well ❤️❤️❤️

**Comment by bradfrost** [comment]
Fantastic, thanks all!

**Pull request merged**
