### PR TITLE
Create matthew-elsom-jekyll-living-styleguide

### PR DESCRIPTION
**Pull request by matthewelsom**

### CODE REVIEW

**Comment by bradfrost** [comment]
@matthewelsom Thanks for sharing! Unfortunately, it looks like the URL https://livingstyleguide.cc/ isn't resolving. Any ideas there? I'll leave this open for a bit while it gets sorted.

**Comment by matthewelsom** [comment]
Sorry about that @bradfrost - I recently updated the URL for this tool. 
I have updated the file to reflect the new name and URL. 
Thanks

**Comment by matthewelsom** [comment]
@bradfrost just checking in to see if this update is ok to merge...?

**Comment by bradfrost** [comment]
Hey @matthewelsom, it's looking like the domain still isn't resolving.

**Pull request merged**
