### PR TITLE
Create dell.md

### PR DESCRIPTION
**Pull request by whitingx**
Addition of Dell's Design Library.

### CODE REVIEW

**Comment by bradfrost** [comment]
Awesome, thanks for sharing!

**Comment by whitingx** [comment]
No problem @bradfrost :)

I notice that the image link seems to be broken on the page though :thought_balloon:

**Comment by michaelthorne** [comment]
@whitingx that image should be working now.

**Comment by whitingx** [comment]
Thanks @michaelthorne :+1:

**Comment by michaelthorne** [comment]
:smiley:

**Pull request merged**
