### PR TITLE
Make URLs pretty

### PR DESCRIPTION
**Pull request by astanush**
Drops the nasty `.html` from page URLs.

Example: styleguides.io/articles.html → styleguides.io/articles

Changed for all pages:
- /articles
- /books
- /examples
- /podcasts
- /talks
- /tools
- [ ] TODO: Add redirect for /podcast
## Redirects

We should add redirects so the old `.html` URLs properly resolve. It looks like you can do this within Github Pages directly:
- https://help.github.com/articles/redirects-on-github-pages/
- https://github.com/jekyll/jekyll-redirect-from/

However, it looks like we're getting into the territory where we need to use Bundler to manage gems.

### CODE REVIEW

**Comment by maban** [comment]
I'm definitely going to merge this, but I'm going to take some time to look into those redirects links you mentioned first. Thanks so much for doing this.

**Comment by astanush** [comment]
It looks like there is a known issue with jekyll-redirect-from and using Collections → https://github.com/jekyll/jekyll-redirect-from/issues/47

I've also [included the error I'm experiencing with our environment](https://github.com/jekyll/jekyll-redirect-from/issues/47#issuecomment-65685216).

**Comment by astanush** [comment]
Looks like the issue might be fixed via https://github.com/jekyll/jekyll-redirect-from/pull/56

**Comment by maban** [comment]
Oooh, I'll check that out! Thanks!

**Pull request closed without merging**
